Company reduxnew
frandk18/caldar-fe pull request #25
Opened 2020-12-30 01:10 UTC by marcosjmelgar

2020-12-30 02:46 UTC, AlexisPucheta requested changes
ahi te deje unos comentarios de cosas que debieran estar en plural

2020-12-30 02:46 UTC, AlexisPucheta commented on src/redux/reducers/rootReducer.js
> +import companyReducer from "./companyReducer";
fijate que los reducers los llamamos en plural, seria companiesReducer. cambiate eso

2020-12-30 02:46 UTC, AlexisPucheta commented on src/components/routes/company/Company.jsx
> +} from "../../../redux/actions/companyActions";
companiesActions

2020-12-30 02:46 UTC, AlexisPucheta commented on src/redux/reducers/companyReducer.js
> +    ADD_COMPANY,
companies

2020-12-30 14:16 UTC, frandk18 commented on src/redux/reducers/companyReducer.js
> +    ADD_COMPANY,
Entiendo que puche hace referencia a la linea: import company ...

2020-12-30 14:17 UTC, frandk18 requested changes
Adhiero a los cambios solicitados por puche.

2021-01-03 14:16 UTC, AlexisPucheta approved these changes, later dismissed

2021-01-03 14:19 UTC, frandk18 approved these changes, later dismissed

2021-01-03 14:22 UTC, AlexisPucheta approved these changes

2021-01-03 14:25 UTC, merged